import { BarChart3, FileText, DollarSign, Users } from 'lucide-react';
import './styles.css';
const Product = () => {
  return (
    <section className="bg-gradient-to-b from-[#121218] via-[#1a1a24] to-black text-white py-32">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-24 relative">
          <h2 className="text-sm uppercase mb-4">Product</h2>
          <h1 className="text-6xl font-bold mb-6 leading-tight bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent">
            Track the things that matter<br />
            <span className="italic">most to you</span>
          </h1>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            From analytics, to integrated sales data to report generating, Scalable has it all.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 max-w-6xl mx-auto">
          {/* Analytics Card */}
          <div className="group bg-[#121218]/50 rounded-2xl p-10 relative overflow-hidden text-center border border-white/10 
                        hover:border-purple-500/50 transition-all duration-300 hover:shadow-2xl hover:shadow-purple-500/10
                        hover:-translate-y-1">
            <div className="absolute inset-0 w-full h-full transition-opacity duration-300 opacity-40 group-hover:opacity-60">
              <div className="blob-gradient absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48" 
                   style={{ filter: 'blur(60px)' }} />
            </div>
            <div className="relative z-10">
              <BarChart3 className="w-16 h-16 mx-auto mb-8 text-purple-400" />
              <h3 className="text-2xl font-semibold mb-4">Simple Analytics</h3>
              <p className="text-gray-400 mx-auto max-w-sm text-lg">
                Empower your choices with insights derived from our real-time data streams.
              </p>
            </div>
          </div>

          {/* Reports Card */}
          <div className="group bg-[#121218]/50 rounded-2xl p-10 relative overflow-hidden text-center border border-white/10 
                        hover:border-purple-500/50 transition-all duration-300 hover:shadow-2xl hover:shadow-purple-500/10
                        hover:-translate-y-1">
            <div className="absolute inset-0 w-full h-full transition-opacity duration-300 opacity-40 group-hover:opacity-60">
              <div className="blob-gradient absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48"
                   style={{ 
                     background: 'linear-gradient(180deg, rgba(255,0,242,0.3), rgba(157,0,255,0.3))',
                     filter: 'blur(60px)'
                   }} />
            </div>
            <div className="relative z-10">
              <FileText className="w-16 h-16 mx-auto mb-8 text-purple-400" />
              <h3 className="text-2xl font-semibold mb-4">Generate Reports with Ease</h3>
              <p className="text-gray-400 mb-6 mx-auto max-w-sm text-lg">
                Easily download reports comprising of data from your sales rep or a custom date range.
              </p>
            </div>
          </div>

          {/* Sales Tracking Card */}
          <div className="group bg-[#121218]/50 rounded-2xl p-10 relative overflow-hidden text-center border border-white/10 
                        hover:border-purple-500/50 transition-all duration-300 hover:shadow-2xl hover:shadow-purple-500/10
                        hover:-translate-y-1">
            <div className="absolute inset-0 w-full h-full transition-opacity duration-300 opacity-40 group-hover:opacity-60">
              <div className="blob-gradient absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48"
                   style={{ 
                     background: 'linear-gradient(180deg, rgba(0,255,255,0.3), rgba(0,100,255,0.3))',
                     filter: 'blur(60px)'
                   }} />
            </div>
            <div className="relative z-10">
              <DollarSign className="w-16 h-16 mx-auto mb-8 text-purple-400" />
              <h3 className="text-2xl font-semibold mb-4">Transparent Sales Tracking</h3>
              <p className="text-gray-400 mb-6 mx-auto max-w-sm text-lg">
                Keep an eye on sales by tracking the revenue generated by every team member.
              </p>
            </div>
          </div>

          {/* Team Members Card */}
          <div className="group bg-[#121218]/50 rounded-2xl p-10 relative overflow-hidden text-center border border-white/10 
                        hover:border-purple-500/50 transition-all duration-300 hover:shadow-2xl hover:shadow-purple-500/10
                        hover:-translate-y-1">
            <div className="absolute inset-0 w-full h-full transition-opacity duration-300 opacity-40 group-hover:opacity-60">
              <div className="blob-gradient absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48"
                   style={{ 
                     background: 'linear-gradient(180deg, rgba(157,0,255,0.3), rgba(0,217,255,0.3))',
                     filter: 'blur(60px)'
                   }} />
            </div>
            <div className="relative z-10">
              <Users className="w-16 h-16 mx-auto mb-8 text-purple-400" />
              <h3 className="text-2xl font-semibold mb-4">Invite Unlimited Team Members</h3>
              <p className="text-gray-400 mx-auto max-w-sm text-lg">
                Don't leave the team behind and easily invite unlimited team members onboard.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Product;